/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeclause_pdf.spliter.project;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfCopy;
import com.itextpdf.text.pdf.PdfImportedPage;
import com.itextpdf.text.pdf.PdfReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author HP
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form Main_Window
     */
    public MainWindow() {
        initComponents();
        setTitle("PDF Splitter Window");
        ImageIcon icon=new ImageIcon(getClass().getResource("pdf.png")); // Icon Source: www.flaticon.com
        setIconImage(icon.getImage());
        FileNameField.setText(System.getProperty("user.dir"));
    }
    public void Break() throws IOException, DocumentException{ // Breaks the pdf file into single page multiple pdfs
        String Path=FileNameField.getText();
        System.out.println("Reading "+Path);
        PdfReader reader=new PdfReader(Path);
        int n=reader.getNumberOfPages();
        System.out.println("No. of the pages in the pdf are: " + n); // These outputs will show up only in the console.
        for (int i=1;i<=n;i++){
            String file="PDF Split_"+i+".pdf";
            Document pdf= new Document(reader.getPageSizeWithRotation(1));
            PdfCopy writer=new PdfCopy(pdf, new FileOutputStream(file));
            pdf.open();
            PdfImportedPage page=writer.getImportedPage(reader, i);
            writer.addPage(page);
            pdf.close();
            writer.close();
        }
        System.out.println("PDF Split Successful");
        OutputLabel.setText("PDF Split was Successful !!!"); // Confirmation of Successful Splitting of PDF
    }   
    
public void break_into() throws IOException, DocumentException{ // extracts the intended (continous) pages and creates a new pdf with those pages
    if("".equals(StartPage.getText()))
         JOptionPane.showMessageDialog(rootPane,"Enter a valid value in the 'From Page' TextField" );
   else if("".equals(EndPage.getText()))
         JOptionPane.showMessageDialog(rootPane,"Enter a valid value in the 'To Page' TextField" );
   else{
            String Path=FileNameField.getText();
            System.out.println("Reading "+Path);
            PdfReader reader=new PdfReader(Path);
            int n=reader.getNumberOfPages();
            int start=Integer.parseInt(StartPage.getText());
            int end=Integer.parseInt(EndPage.getText());
            String file="PDF-Split"+".pdf";
            Document pdf= new Document(reader.getPageSizeWithRotation(1));
            PdfCopy writer=new PdfCopy(pdf, new FileOutputStream(file));
            for(int i=start;i<=end;i++){            
                pdf.open();
                PdfImportedPage page=writer.getImportedPage(reader, i);
                writer.addPage(page);
            }
            pdf.close();
            writer.close();
            System.out.println("PDF Split Successful");
            StartPage.setText("");// To Reset the values
            EndPage.setText("");//    of the TextFields
            OutputLabel.setText("PDF Split was Successful !!!");  // Confirmation of Successful Splitting of PDF
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FileNameField = new javax.swing.JTextField();
        BrowseButton = new javax.swing.JButton();
        SplitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StartPage = new javax.swing.JTextField();
        EndPage = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        OutputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Select the file to split");

        BrowseButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BrowseButton.setText("Browse");
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });

        SplitButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SplitButton.setText("Split PDF");
        SplitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SplitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Split From Page");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("To Page");

        StartPage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        EndPage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton1.setText("Split into individual pages");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        OutputLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BrowseButton)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StartPage, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(EndPage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton1)
                        .addGap(58, 58, 58))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(SplitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(OutputLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseButton))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(StartPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(EndPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(SplitButton)
                .addGap(29, 29, 29)
                .addComponent(OutputLabel)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        JFileChooser chooser=new JFileChooser();
        FileNameExtensionFilter TextFile=new FileNameExtensionFilter("Only pdf Files (.pdf)", "pdf"); // to ensure only
        chooser.setAcceptAllFileFilterUsed(false);                                                                                //  pdfs are shown to the user
        chooser.addChoosableFileFilter(TextFile);                                                                              //    in the browse dialog box  
        chooser.showOpenDialog(null);                                                                                                 
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        FileNameField.setText(filename);
    }                                            

    private void SplitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        try {
            if(jRadioButton1.isSelected())
                Break();
            else{
                break_into();
            }             
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }                                           

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(jRadioButton1.isSelected()){
            StartPage.setEnabled(false); // To disable the TextFields if the user wants to split every page
            EndPage.setEnabled(false);
        }
        else{
            StartPage.setEnabled(true);
            EndPage.setEnabled(true);        
            }
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BrowseButton;
    private javax.swing.JTextField EndPage;
    private javax.swing.JTextField FileNameField;
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JButton SplitButton;
    private javax.swing.JTextField StartPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration                   
}